name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: ls -a via OPEN SSH Private Key
            uses: fifsky/ssh-action@master
            with:
              command: |
                cd /test
                ls -a
                echo "env_var:$FIRST_NAME"
                exit 1
              host: ${{ secrets.HOST }}
              user: ubuntu
              key: ${{ secrets.KEY}}
              args: "-tt -vvv"