name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Login to GitHub Container Registry
      run: curl docker login gchr.io/ -u ${{ github.repository_owner }} -p ${{ secrets.TOKEN }}

    - name: Test build
      run: curl docker build -t test_image .
 
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/test_image:latest



