name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push testImage
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test_image:latest

    - name: ls -a via OPEN SSH Private Key
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd test
          ls -a
          docker login -u ${{ github.repository_owner }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          
          docker rmi cpplovelove/cicd:latest
          docker pull cpplovelove/test_image:latest
          
          cd CI-CD_test$
          ./build.sh

          exit 0

        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.KEY}}
        args: "-tt -vvv"
          