name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push testImage
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository_owner }}/test_image:latest

    - name: Pull testImage to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username : ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script_stop: true
        script: |
          sudo -S apt install jq
          docker login -u ${{ github.repository_owner }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          