name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push testImage
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test_image:latest


    - name: Load private SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY }}

    - name: Atomic Deploy
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          whoami
        EOF


    - name: Pull testImage to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username : ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: whoami
          