name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push testImage
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test_image:latest

    - name: Deploy in EC2
      env:
          PRIVATE_KEY: ${{ secrets.KEY  }}
          HOSTNAME : ${{ secrets.HOST  }}
          USER_NAME : ${{ secrets.USERNAME  }}
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.USERNAME  }}@${{ secrets.HOST  }}        
        
          #ssh -i "symoon_saba_key_gen.pem" ${{ secrets.USERNAME  }}@${{ secrets.HOST  }}        
          whoami
          #Now we have got the access of EC2 and we will start the deploy .
          
        


