name: localTest

on:
  push:
    branches: [main]

jobs:
  test:
    name: push image to github registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Login to GitHub Container Registry
      run: curl docker login gchr.io/ -u ${{ github.repository_owner }} -p ${{ secrets.TOKEN }}

    - name: Build and Push 
      run: | 
        curl docker build -t test_image .
        docker tag 5fa570368df9 ghcr.io/cpplovelove/test_image:lts 
        docker push ghcr.io/<cpplovelove>/test_image:lts
